### ISSUE TITLE
Ice cream

### ISSUE THREAD

**Issue by SBEnki** [shuqin19/shuqin19#3]
Hi, 

there is a lack of a guide to making the ice cream. Think you should attach protocol.

![image](https://user-images.githubusercontent.com/62359649/77580186-c9ec1c80-6e98-11ea-995a-4146c669b51f.png)

**Comment by shuqin19** [comment]
How did you put image here?

**Comment by SBEnki** [comment]
hi, you need to do:

!image(URL of image). 

I will check how we add it via image not in URL

**Comment by shuqin19** [comment]
!matcha(https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQXRApgHO9O56aXLzLUEBLO_2K_-X2-0RkHLr0VvurEwCRRGgoK)

**Comment by shuqin19** [comment]
![matcha ice cream](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQXRApgHO9O56aXLzLUEBLO_2K_-X2-0RkHLr0VvurEwCRRGgoK)

**Comment by shuqin19** [comment]
Thanks!

**Comment by SBEnki** [comment]
ok, so you can just do the same to copy and paste an image from desktop

![image](https://user-images.githubusercontent.com/62359649/77581853-aecedc00-6e9b-11ea-8e7b-8195e3c3c360.png)
